name: Android CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Dar permissão ao Gradlew
        run: chmod +x ./gradlew

      - name: Executar testes
        run: ./gradlew test # Executa testes unitários

      - name: Build do APK Debug
        run: ./gradlew assembleDebug # Gera arquivo .apk

      - name: Build do AAB Release
        run: ./gradlew :app:bundleRelease # Gera Android App Bundle

      - name: Upload APK Debug
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/

      - name: Upload AAB Release
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: app/build/outputs/bundle/release/
